CREATE DATABASE `spider` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci */;
CREATE TABLE article
(
  id      VARCHAR(50) PRIMARY KEY NOT NULL,
  title   VARCHAR(255),
  content LONGTEXT,
  time    VARCHAR(50),
  tags    VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE channel
(
  id VARCHAR(50) PRIMARY KEY NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;